server:
  port: 8080

spring:
  application:
    name: partnermaneger
  datasource:
    url: jdbc:h2:mem:partnermaneger_db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: "/h2-console"
      enable: true

api:
  security:
    token:
      secret: "vLXu1AR6AdIQ1noDICPCEYaWc/+V9mF9Ir3xypsYdL8="
      expiration: 240